@Library('local-shared-lib') _

pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        ECR_REPO = "jenkins-demo-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                buildDocker()
            }
        }

        stage('Push Image to ECR') {
            steps {
                pushToECR()
            }
        }

        stage('Deploy to EC2') {
            steps {
                deployToEC2()
            }
        }

    }
}